Add unit tests for building package. Standalone and Mobile
Doesn't pass for Android. Get the following error:
Exception: Cannot include plugin 'Assets/LSL4Unity/Plugins/LSL/Windows/x64/lsl.lib' (Key: lsl.lib;None) since plugin with the same name and architecture was already added ('Assets/LSL4Unity/Plugins/LSL/Windows/x86/lsl.lib (Architecture: None)').

Building for Android seems to be a bigger issue based on issues #60 and #61